function grammarPrompt(rule: string) {
  return `You are an English writing teacher and I am your student. I want to learn how to use ${rule} correctly in different situations. Please explain the rules and examples of ${rule} and then give me some exercises to practice it.`;
}

function speakingPrompt(fixGrammar = true) {
  return `I want you to act as a spoken English teacher and help me improve. I will speak to you in English and you will reply to me in English to practice my spoken English. I want you to keep your reply neat, limiting the reply to 100 words. ${
    fixGrammar ? 'I want you to strictly correct my grammar mistakes, typos, and factual errors.' : ''
  } I want you to ask me a question in your reply. Now let’s start practicing, you could ask me a question first. ${
    fixGrammar ? 'Remember, I want you to strictly correct my grammar mistakes, typos, and factual errors.' : ''
  }`;
}

// games. guess a word
// https://learnenglish.britishcouncil.org/skills/speaking/b2-speaking

export const prompts = [
  {
    topic: 'Speaking and Listening',
    list: [
      { title: 'Correct grammar mistakes', text: speakingPrompt() },
      { title: 'Do not correct grammar mistakes', text: speakingPrompt(false) },
    ],
  },
  {
    topic: 'Writing',
    list: [
      'Your task is to act as an English writing teacher and editor. You will receive a text from me and you will rewrite it using better vocabulary and grammar. You will also make sure that the text is clear, coherent and engaging for the reader.',
    ],
  },
  {
    topic: 'Role Play',
    list: [
      {
        title: 'Shop assistant',
        text: 'I’d like you to act like an assistant in a shop who is trying to sell me a product that I don’t need.',
      },
      {
        title: 'Job interviewer',
        text: 'I’d like you to act like an interviewer who is very impressed by my resume and wants to hire me on the spot.',
      },
      {
        title: 'Bank manager',
        text: 'I’d like you to act like a bank manager who is very rude and unhelpful when I ask for a loan.',
      },
      {
        title: 'Traveler',
        text: 'I’d like you to act like a traveler who is very curious and enthusiastic about the city that I live in.',
      },
      {
        title: 'Check in to the hotel',
        text: 'I’d like you to act like a reception manager who is very friendly and helpful when I check in to the hotel',
      },
      {
        title: 'Reception manager who is very very apologetic and offers me a compensation',
        text: 'I’d like you to act like a reception manager who is very apologetic and offers me a compensation when I complain about the noise in my room.',
      },
      {
        title: 'Reception manager who is very suspicious',
        text: 'I’d like you to act like a reception manager who is very suspicious and accuses me of stealing something from the hotel.',
      },
      {
        title: 'Busy and impatient reception manager',
        text: 'I’d like you to act like a reception manager who is very busy and impatient when I ask for some information about the city.',
      },
      {
        title: 'Veterinarian',
        text: 'I’d like you to act like a kind veterinarian who examines my dog and tells me what’s wrong with him.',
      },
      {
        title: 'Doctor',
        text: 'I’d like you to act like a kind doctor who listens to my symptoms and diagnoses me.',
      },
    ],
  },
  {
    topic: 'Grammar',
    list: [
      'The Present Simple Tense',
      'The verb must',
      'To be (am, is, are)',
      'The Present Continuous Tense',
      'The Present Simple Tense vs The Present Continuous Tense',
      'To be (was, were)',
      'The Past Simple Tense',
      'Be going to',
      'The Future Simple Tense',
      'The modal verb "can"',
      'The verb "have to',
      'The verb "have got"',
      'Infinitive of purpose',
      'Imperative',
      "Let's",
      'Would like',
      'Articles A and An',
      'Zero article',
      'The definite article',
      'Uncountable nouns',
      'Plurals',
      'Possessive nouns',
      'Personal pronouns',
      'Possessive adjectives',
      'Demonstrative pronouns',
      'Some, any, no',
      'The comparative degree of adjectives',
      'The superlative degree',
      'Quantifiers (many/much/a lot of)',
      'Cardinal numbers',
      'Ordinal numbers',
      'There is, there are',
      'Dummy it',
      'Question words',
      'Conjunctions and, or, but, because',
      "Possessive case of a noun (Ann's phone, my dad's car)",
      'Singular and plural nouns',
      'Usage of some, any, no with nouns',
      'Much, many, a lot',
      '(A) little, (a) few',
      'Usage of all / none, both / neither, some / most with nouns',
      'The indefinite article a (an)',
      'The definite article THE',
      'No article',
      'Article the with geographical names',
      'Adjectives',
      'Adjectives with -ed and -ing',
      'Comparative of adjectives',
      'Superlative of adjectives',
      'Types of comparisons',
      'Types of adverbs',
      'Adverbs and word order',
      'Comparative of adverbs',
      'Superlative of adverbs',
      'Pronouns I — me, he — him, we — us, they — them ',
      'Posessive pronouns my, your, his, her, its, our, their',
      'Pronouns this, that, these, those',
      'Pronouns somebody, someone, something, anything',
      'Time',
      'Dates',
      'Prepositions of place',
      'Prepositions of movement',
      'Prepositions of time (at, in, on)',
      'Present Simple of the verb to be',
      'Past Simple of the verb to be',
      'there is / are',
      'Present Simple (usage)',
      'Present Simple (formation)',
      'Present Continuous (usage)',
      'Present Сontinuous (formation)',
      'Present Perfect (usage)',
      'Present Perfect (formation)',
      'Present Perfect Continuous (usage)',
      'Present Perfect Continuous (formation)',
      'Present Simple or Present Continuous',
      'Present Perfect vs Present Perfect Continuous',
      'Past Simple (usage)',
      'Past Simple (formation)',
      'Used to',
      'Past Continuous (usage)',
      'Past Continuous (formation)',
      'Past Simple or Past Continuous',
      'Past Simple or Present Perfect',
      'Past Perfect (usage)',
      'Past Perfect (formation)',
      'Future Simple (usage)',
      'Future Simple (formation)',
      'Future Continuous (usage)',
      'Future Continuous (formation)',
      'Future Perfect (usage)',
      'Future Perfect (formation)',
      'Future Perfect Continuous (usage)',
      'Future Perfect Continuous (formation)',
      'to be going to',
      'Future Time Expressions',
      'Modal verb can',
      'Modal verb must and have to',
      'Modal verb should',
      'Modal verb ought to',
      'Modals for abilities',
      "Might, may, must, can't, could",
      'Modals for rules and regulations',
      'Modals for prohibitions',
      'Passive Voice',
      'Passive Voice with modal verbs',
      'The Causative: have something done',
      'Infinitive after the verbs want и would like',
      'Gerunds after like / love / enjoy / hate',
      'Verb + gerund (ing-form)',
      'Verb + infinitive',
      'Verb + infinitive or -ing form',
      'Word order in questions',
      'Direct and indirect questions ',
      'Zero Conditional',
      'First Conditional',
      'Second Conditional',
      'Third Conditional',
      'Mixed Conditional',
      'Wish / If only',
      'Reported orders and requests',
      'Linkers and, but, so, because',
      'Relative clauses',
      'Posessive forms of nouns',
      'Countable and uncountable nouns',
      'Quantifiers a lot of, much, many, (a) little, (a) few',
      'Articles',
      'Comparison of adjectives',
      'Comparison  of adverbs',
      'Adverbs',
      'Reflexive pronouns',
      'Indefinite pronouns',
      'Relative pronouns',
      'Verbs to be, have, have got',
      'Present Simple vs Continuous',
      'Present Perfect',
      'Past Simple',
      'Past Simple vs Past Continuous',
      'Past Perfect',
      'Used to and would',
      'Future forms',
      'Modals for ability and possibility',
      'Modals for permission and obligation',
      'Modals for necessity, lack of necessity',
      'Subject and Object Questions',
      'Infinitive',
      'Gerund and Participle I',
      'Conditionals',
      'Reported statements',
      'Reported questions',
      'Types of word formation',
      'Prefixes and suffixes',
      'Formation of nouns',
      'Nouns for jobs',
      'Nouns for nationalities',
      'Formation of adjectives',
      'Negative prefixes with adjectives',
      'Compound nouns',
      'Compound adjectives',
      'Formation of verbs',
      'Formation of adverbs',
      'Conversion',
      'Writing an email',
      'Writing a postcard',
      'Writing a short story',
      'Writing an invitation letter',
      'Reading aloud',
      'Describing a photo',
      'Comparing photos',
      'Writing a review',
      'Writing a short biography',
    ].map((item) => ({
      title: item,
      text: grammarPrompt(item),
    })),
  },
  {
    topic: 'Conversation Topics',
    list: [
      'Let\'s have a conversation about "Tea Talk"',
      'Let\'s have a conversation about "Weather"',
      'Let\'s have a conversation about "Learning English"',
      'Let\'s have a conversation about "Your best morning"',
      'Let\'s have a conversation about "Films and series"',
      'Let\'s have a conversation about "Computer games"',
      'Let\'s have a conversation about "Cultural appropriation"',
      'Let\'s have a conversation about "Project Management"',
      'Let\'s have a conversation about "Leadership"',
      'Let\'s have a conversation about "Elevator pitch"',
      'Let\'s have a conversation about "Korean cinema"',
      'Let\'s have a conversation about "Networking"',
      'Let\'s have a conversation about "Memes"',
      'Let\'s have a conversation about "Silicon Valleys around the world"',
      'Let\'s have a conversation about "The paranormal"',
      'Let\'s have a conversation about "Family and career choice"',
      'Let\'s have a conversation about "Job interview"',
      'Let\'s have a conversation about "Cryptocurrency"',
      'Let\'s have a conversation about "Facts about the world"',
      'Let\'s have a conversation about "Memories of my school days"',
      'Let\'s have a conversation about "Challenges"',
      'Let\'s have a conversation about "Tesla"',
      'Let\'s have a conversation about "Life after sport"',
      'Let\'s have a conversation about "Personality"',
      'Let\'s have a conversation about "Britney Spears"',
      'Let\'s have a conversation about "Space travel"',
      'Let\'s have a conversation about "Summer is a little life"',
      'Let\'s have a conversation about "At the hotel"',
      'Let\'s have a conversation about "Travelling"',
      'Let\'s have a conversation about "Music festivals"',
      'Let\'s have a conversation about "Local cuisine"',
      'Let\'s have a conversation about "How to travel for cheap"',
      'Let\'s have a conversation about "Friendship"',
      'Let\'s have a conversation about "Life in nature"',
      'Let\'s have a conversation about "Sports"',
      'Let\'s have a conversation about "The love for coffee"',
      'Let\'s have a conversation about "Wedding traditions"',
      'Let\'s have a conversation about "What makes us happy?"',
      'Let\'s have a conversation about "Restaurant problems"',
      'Let\'s have a conversation about "Bloggers"',
      'Let\'s have a conversation about "Beauty"',
      'Let\'s have a conversation about "How to get rid of relationship"',
      'Let\'s have a conversation about "Makeup"',
      'Let\'s have a conversation about "How to read every day"',
      'Let\'s have a conversation about "DIY‌"',
      'Let\'s have a conversation about "Psychology"',
      'Let\'s have a conversation about "Role play: At the Airport"',
      'Let\'s have a conversation about "Build your startup!"',
      'Let\'s have a conversation about "Veganism"',
      'Let\'s have a conversation about "Your favourite series"',
      'Let\'s have a conversation about "YouTube and video platforms"',
      'Let\'s have a conversation about "Remote working"',
      'Let\'s have a conversation about "Junk food and healthy lifestyle"',
      'Let\'s have a conversation about "Fighting stress"',
      'Let\'s have a conversation about "Your dream home"',
      'Let\'s have a conversation about "Music"',
      'Let\'s have a conversation about "Books"',
      'Let\'s have a conversation about "Philosophy"',
      'Let\'s have a conversation about "Child-rearing"',
      'Let\'s have a conversation about "Your neighbours"',
      'Let\'s have a conversation about "Old Russian films"',
      'Let\'s have a conversation about "Cats, dogs and other pets"',
      'Let\'s have a conversation about "How to calm your mind"',
      'Let\'s have a conversation about "Relationships"',
      'Let\'s have a conversation about "Job"',
      'Let\'s have a conversation about "Gadget addiction"',
      'Let\'s have a conversation about "Luxury"',
      'Let\'s have a conversation about "Art"',
      'Let\'s have a conversation about "Culture and stereotypes"',
      'Let\'s have a conversation about "Australia"',
      'Let\'s have a conversation about "Food and cuisines"',
      'Let\'s have a conversation about "The art of photography"',
      'Let\'s have a conversation about "Mother\'s Day"',
      'Let\'s have a conversation about "Texas"',
      'Let\'s have a conversation about "Gender Stereotypes"',
      'Let\'s have a conversation about "Scandinavian countries"',
      'Let\'s have a conversation about "Political debate"',
      'Let\'s have a conversation about "Role Play: At the doctor\'s"',
      'Let\'s have a conversation about "Favourite sweets"',
      'Let\'s have a conversation about "Jokes"',
      'Let\'s have a conversation about "India and Hinglish"',
      'Let\'s have a conversation about "Schools around the world"',
      'Let\'s have a conversation about "Dating"',
      'Let\'s have a conversation about "Family and traditions"',
      'Let\'s have a conversation about "Your country"',
      'Let\'s have a conversation about "Garbage and recycling"',
      'Let\'s have a conversation about "Sleep"',
      'Let\'s have a conversation about "The British royal family"',
      'Let\'s have a conversation about "Animals"',
      'Let\'s have a conversation about "London"',
      'Let\'s have a conversation about "Truth or Dare?"',
      'Let\'s have a conversation about "Charades game"',
      'Let\'s have a conversation about "Presents"',
      'Let\'s have a conversation about "Travel issues"',
      'Let\'s have a conversation about "Home description"',
      'Let\'s have a conversation about "Steve Jobs"',
      'Let\'s have a conversation about "Body positivity"',
      'Let\'s have a conversation about "Role play: Asking and giving directions"',
      'Let\'s have a conversation about "Role play: Grocery shopping"',
      'Let\'s have a conversation about "Quentin Tarantino\'s films"',
      'Let\'s have a conversation about "Household chores"',
      'Let\'s have a conversation about "South Africa: the Rainbow Nation"',
      'Let\'s have a conversation about "Role-play: Shopping for clothes"',
      'Let\'s have a conversation about "Bali"',
      'Let\'s have a conversation about "Singapore"',
      'Let\'s have a conversation about "Japan"',
      'Let\'s have a conversation about "Comic-Con"',
      'Let\'s have a conversation about "IELTS Talks: Work and study"',
      'Let\'s have a conversation about "IELTS Talks: Accommodation"',
      'Let\'s have a conversation about "IELTS Talk: Basic skills"',
      'Let\'s have a conversation about "IELTS Talk: Art"',
      'Let\'s have a conversation about "Exam Talks: Hobbies"',
      'Let\'s have a conversation about "IELTS Talk: Shopping"',
      'Let\'s have a conversation about "Hobbies"',
      'Let\'s have a conversation about "St. Valentine\'s Day"',
      'Let\'s have a conversation about "New Year"',
      'Let\'s have a conversation about "Holiday Movies"',
      'Let\'s have a conversation about "Thanksgiving Day"',
      'Let\'s have a conversation about "Black Friday"',
      'Let\'s have a conversation about "Halloween"',
      "Let's have a conversation about \"'Save New Year' Quest\"",
      'Let\'s have a conversation about "Labour Day"',
      'Let\'s have a conversation about "Happy Easter"',
      'Let\'s have a conversation about "Victory Day"',
    ],
  },
];
